Fix bug where the command name is replaced with 'paropts-test'
Before, when the user of the client program uses an incorrect option,
they would see the message:
ERROR: Incorrect option <wrong_option>
Type 'paropts-test --help' for usage
whereas the last line should read:
Type '<command_name> --help' for usage